#!/usr/bin/env bash
# pre-push hook (game repo) — two jobs:
#   1. Block any commit whose message/body contains Claude session URLs or
#      other personal identifiers (see CLAUDE.md "No Personal Identifiers").
#   2. Run the browser verifier (verify.sh) when app source files are pushed.
#
# Installed into .git/hooks/pre-push by .claude/settings.json on session start.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Read push info from stdin; skip entirely for branch deletions.
PUSH_INFO=$(cat)
if echo "$PUSH_INFO" | grep -q "^0000000000000000000000000000000000000000 "; then
  exit 0  # delete push — nothing to verify
fi
if [ -z "$PUSH_INFO" ]; then
  exit 0  # nothing being pushed
fi

# Commit range for this push (remote-sha..local-sha).
RANGE=$(echo "$PUSH_INFO" | awk '{print $4 ".." $2}' | head -1)
[ -n "$RANGE" ] || exit 0

# ── 1. Personal-identifier guard ───────────────────────────────────────────
# Bans: Claude session URLs, Claude-Session trailers, and the auto-generated
# "Generated by/with Claude Code" footers — in the subject or the body.
PII_PATTERN='claude\.ai/code/session_[A-Za-z0-9]|Claude-Session:|Generated (by|with) \[?Claude Code'
bad=$(git log --format="%h%n%B" "$RANGE" 2>/dev/null | grep -iE "$PII_PATTERN" || true)
if [ -n "$bad" ]; then
  echo "ERROR: commit message/body contains a personal identifier (violates CLAUDE.md):" >&2
  echo "$bad" >&2
  echo "Rewrite the offending commit message(s) before pushing." >&2
  exit 1
fi

# ── 2. Browser verifier on source changes ──────────────────────────────────
# Run the full smoke test when any app source file is in the push.
if git diff --name-only "$RANGE" 2>/dev/null \
     | grep -qE '\.(js|css|html|json)$|^assets/'; then
  if [ -f "$REPO_ROOT/verify.sh" ]; then
    bash "$REPO_ROOT/verify.sh"
  fi
fi
